trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: CreateDev
  displayName: 'Deploy to Dev Account'
  jobs:
  - job: BuildPackage
    displayName: 'Deploy to Dev Account'
    steps:
    - checkout: none
    - download: current
      artifact: 'packages'
    - task: TfxInstaller@3
      displayName: 'Install tfx-cli'
      inputs:
        version: 'v0.7.x'
    - script: echo Deploy to Dev Account

- stage: DeployProd
  displayName: 'Deploy to Production Account'
  jobs:
  - job: BuildPackage
    displayName: 'Deploy to Production Account'
    steps:
    - checkout: none
    - download: current
      artifact: 'packages'
    - task: TfxInstaller@3
      displayName: 'Install tfx-cli'
      inputs:
        version: 'v0.7.x'
    - script: echo Deploy to Production Account
