trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: 'system.debug'
  value: true
- name: 'version.major'
  value: '1'
- name: 'version.minor'
  value: '0'
- name: 'version.revision'
  value: $(Build.BuildId)

stages:
- stage: BuildPackage
  displayName: 'Build and Package'
  jobs:
  - job: BuildPackage
    displayName: 'Build and Package'
    steps:
    
    - script: npm i
      displayName: 'Install NPM packages'

    - task: TfxInstaller@3
      displayName: 'Install tfx-cli'
      inputs:
        version: 'v0.7.x'

    - script: npm run build
      displayName: 'Build'

    - task: RegExMatchReplace@1
      inputs:
        WorkingDirectory: '$(Pipeline.Workspace)'
        PathToFile: '*/**/task.json'
        RegEx: 'TASK_ID'
        ValueToReplace: '$(task.id.development)'

    - task: PackageAzureDevOpsExtension@3
      displayName: 'Package for testing'
      inputs:
        rootFolder: 
        publisherId: '$(publisher.id.development)'
        extensionName: '[Dev] Post To Office 365 Connector'
        extensionVersion: '$(version.major).$(version.minor).$(version.revision)'
        updateTasksVersion: true
        outputPath: '$(Build.ArtifactStagingDirectory)'

    - task: RegExMatchReplace@1
      inputs:
        PathToFile: '/**/task.json'
        RegEx: '$(task.id.development)'
        ValueToReplace: '$(task.id.production)'

    - task: PackageAzureDevOpsExtension@3
      displayName: 'Package for prod'
      inputs:
        rootFolder: 
        publisherId: '$(publisher.id.production)'
        extensionName: 'Post To Office 365 Connector'
        extensionVersion: '$(version.major).$(version.minor).$(version.revision)'
        updateTasksVersion: true
        outputPath: '$(Build.ArtifactStagingDirectory)'
  
    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: 'packages'
