# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TfxInstaller@
  displayName: 'Install tfx-cli'
  inputs:
    version: "v0.8.x"
    autoUpdate: true

- script: mpm i
  displayName: 'Install NPM packages'

- script: npm run build
  displayName: 'Build'

- script: tfx extension create --manifest-globs vss-extension.json --publisher "freerangeeggs-dev" --extension-id "[Dev] PostToOffice365Connector"
  displayName: 'Package for Development'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
