# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TfxInstaller@3
  displayName: 'Install tfx-cli'
  inputs:
    version: 'v0.7.x'
    
- script: npm i
  displayName: 'Install NPM packages'

- script: npm run build
  displayName: 'Build'

# - script: tfx extension create --manifest-globs vss-extension.json --publisher ""
#   displayName: 'Package for Development'

- task: PackageAzureDevOpsExtension@3
  inputs:
    rootFolder: 
    publisherId: 'freerangeeggs-dev'
    extensionName: '[Dev] Post To Office 365 Connector'
    extensionVersion: '1.0.$(BuildId)'
    updateTasksVersion: false

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
