trigger:
- none

stages:
- stage: TestUbuntu
  displayName: 'Test on ubuntu-latest'
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: 'test'
    steps:
    - task: PostToOffice365Connector@1
      inputs:
        url: '$(WebhookUrl)'
        title: 'Test post'
        msg: 'TESTING UBUNTU'

- stage: TestWindows
  displayName: 'Test on windows-latest'
  pool:
    vmImage: 'windows-latest'
  jobs:
  - job: 'test'
    steps:
    - task: PostToOffice365Connector@1
      inputs:
        url: '$(WebhookUrl)'
        title: 'Test post'
        msg: 'TESTING WINDOWS'
