trigger:
- none

stages:
- stage: TestUbuntu
  displayName: 'Test on ubuntu-latest'
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: 'test'
    steps:
    - task: $(TaskId)
      inputs:
        url: '$(TeamsWebhookUrl)'
        title: 'Test post'
        msg: 'TESTING UBUNTU'

- stage: TestWindows
  displayName: 'Test on windows-latest'
  pool:
    vmImage: 'windows-latest'
  jobs:
  - job: 'test'
    steps:
    - task: $(TaskId)
      inputs:
        url: '$(TeamsWebhookUrl)'
        title: 'Test post'
        msg: 'TESTING WINDOWS'

- stage: TestGroupsConnector
  displayName: 'Test on windows-latest'
  pool:
    vmImage: 'windows-latest'
  jobs:
  - job: 'test'
    steps:
    - task: $(TaskId)
      inputs:
        url: '$(OutlookWebhookUrl)'
        title: 'Test post'
        msg: 'TESTING Outlook Groups COnnector'
